### ISSUE TITLE
NodeJS Update?

### ISSUE THREAD

**Issue by olifre** [MyAlbum/purge-cache#6]
When using this action, a warning is displayed:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: MyAlbum/purge-cache@v2.1.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

**Comment by Arjan-Zuidema** [comment]
Updated to node 20

**Comment by olifre** [comment]
Many thanks, great to get rid of the warning :-). 

I just realized the latest release is not yet pushed as a tag here:
https://github.com/MyAlbum/purge-cache/tags
(and the v2 tag is not updated yet), maybe `git push` for the tags was missing? 

Thanks in advance!

**Comment by Arjan-Zuidema** [comment]
v2 tag has been updated already https://github.com/MyAlbum/purge-cache/releases/tag/v2

**Comment by olifre** [comment]
Many thanks! 
That's strange, running an action in my repo using `@v2` I do get:
```
Warning: Unexpected input(s) 'accessed', 'created', valid inputs are ['debug', 'max-age', 'token']
Run MyAlbum/purge-cache@v2
```
i.e. it seems to use an older version (and also the `Node.js 16` warning is still there). 

That's using `MyAlbum/purge-cache@v2`.

**Comment by Arjan-Zuidema** [comment]
I'll look into it next week

**Comment by ardittristan** [comment]
v2 seems to still be using an older commit https://github.com/MyAlbum/purge-cache/compare/v2...master
![image](https://github.com/MyAlbum/purge-cache/assets/42787508/bc63d052-c973-4d7d-a918-a682b994f6d2)

**Comment by olifre** [comment]
Indeed, I can confirm the warnings:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: MyAlbum/purge-cache@v2.
 For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Unexpected input(s) 'accessed', 'created', valid inputs are ['debug', 'max-age', 'token']
```
are still present using `@v2`.

**Comment by emmahsax** [comment]
@Arjan-Zuidema Right, the new tag wasn't created properly, and `@v2` wasn't updated either. I solved it by locking it down to a SHA:

```yaml
steps:
  - uses: MyAlbum/purge-cache@881eb5957687193fa612bf74c0042adc78ea5e54
```

Clearly not ideal, but better than the annoying annotations all over the place!

**Comment by Arjan-Zuidema** [comment]
I just re-created v2.2.0 tag, let me know if it works now

**Comment by olifre** [comment]
> I just re-created v2.2.0 tag, let me know if it works now

Many thanks, I can confirm that fixes it for me when explicitly using the `@v2.2.0` tag! :+1: 
The `@v2` tag still seems to reference an older version, though, instead of being identical to the latest Version 2 tag.

**Comment by Arjan-Zuidema** [comment]
@olifre I changed the latest release to v2, is this better now? 🙂

Both v2 and v2.2.0 should point to te latest version

**Comment by olifre** [comment]
Many thanks, I can confirm that did the trick, my latest action run at:
https://github.com/unibonn/datenauswertung-install/actions/runs/10942926866
used `@v2` now and no NodeJS warnings and no complaints about the new parameters :+1: . Many thanks!
