### ISSUE TITLE
Git tag missing for latest version

### ISSUE THREAD

**Issue by sscheib** [MyAlbum/purge-cache#9]
I am using [renovate](https://docs.renovatebot.com/) to keep GitHub actions on my repository up-to-date.
Renovate checks for Git tags, where the latest available tag is [v2.1.0](https://github.com/MyAlbum/purge-cache/releases/tag/v2.1.0), although v2.2.0 has been released with a bump to Node 20.

If it's feasible on your end, could you please create a git tag v2.2.0 to reflect the current GitHub release v2.2.0?

Unfortunately, I have no way of working around this in renovate, otherwise I would have done this instead of bothering you here.

Thanks, and all the best,
Steffen

**Comment by curtdept** [comment]
@Arjan-Zuidema it looks like the build failed and this never pushed or published under the v2 tag. When using this tag its picking up older versions (not node 20 2.2.0)

**Comment by emmahsax** [comment]
I posted a temporary answer here: https://github.com/MyAlbum/purge-cache/issues/6#issuecomment-2358806267

> Right, the new tag wasn't created properly, and `@v2` wasn't updated either. I solved it by locking it down to a SHA:
> 
> ```yaml
> steps:
>   - uses: MyAlbum/purge-cache@881eb5957687193fa612bf74c0042adc78ea5e54
> ```
>
> Clearly not ideal, but better than the annoying annotations all over the place!

Unfortunately the true answer won't be solved until somebody with permissions comes back to fix the tags.

**Comment by Arjan-Zuidema** [comment]
I'll see if I have time tomorrow to fix the tags

**Comment by Arjan-Zuidema** [comment]
I created a new v2.2.0 tag, let me know if it works now :)

**Comment by Arjan-Zuidema** [comment]
Closing this as v2 and v2.2.0 tags both point to the latest version

**Comment by curtdept** [comment]
Looks good now on the v2 tag thanks.
